definitions:
  okresponse.Success:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /healthz:
    get:
      description: Health check API
      responses:
        "200":
          description: '{\"msg\":\"ok\"}'
          schema:
            $ref: '#/definitions/okresponse.Success'
      summary: Healthz API
  /hello:
    get:
      description: Hello test API
      responses:
        "200":
          description: '{"msg":"ok"}'
          schema:
            $ref: '#/definitions/okresponse.Success'
      summary: Hello API
  /metrics:
    get:
      description: Metrics API
      summary: Metrics API
swagger: "2.0"
